### PR TITLE
Fix split

### LINKED ISSUE #71: BUG: `split_search` does not split correctly in some cases
While benchmarking domain splitting between different approaches, I noticed that `split_search` script does not do some splits correctly.

Example on Barnacle: `/projects/microprot/results/domain_benchmark/pkg/01-PDB/T0831.{out,match,non_match}`
HHSearch clearly hits 1 PDB which should be the hit (residues "1-419" in target). However, for an unknown reason, the script decided to `match` residues "1-80" (*i.e. only the first line of alignment in out*) and leave "81-419" as a `non_match`. The problem then continues in `../02-CM`, where again we hit a single PDB with 100% probability, but the method only assigns `match` to residues "163-242" (i.e. only the second line*) and the rest is `non_match`

Parameters used:
```
split_PDB:
    params:
        min_prob: 95.0
        min_fragment_length: 40

split_CM:
    params:
        max_evalue: 0.1
        min_fragment_length: 40
```
or view the entire config on Barnacle in: `/projects/microprot/results/domain_benchmark/config.yml`

The fix is not very time-sensitive, but it would be nice to have before the end of the year.

### PR DESCRIPTION
**Pull request by sjanssen2**
Fixed #71 
Hit name is identified as start of line up to number that reports hit coordinates. Problem arises if this number is suffix of the name. We need to start the line from back to front, not front to back!

### CODE REVIEW

**Comment by sjanssen2** [comment]
ready for a review @tkosciol 
The Travis error is nothing I touched, did we ignore it before?

**Comment by tkosciol** [comment]
Travis error looks safe to ignore. this was the case before, too and we had no problems.
So, basically the only difference is changing `find` to `rfind` - wow!

Looks good, thanks @sjanssen2 !!!

**Comment by sjanssen2** [comment]
@qiyunzhu am I right that the code that flake8 is complaining about (ambiguous variables) is of your production? Should you feel bored in China, you could do me a favor and clean that up. But it is really not urgent. Thanks.

**Comment by qiyunzhu** [comment]
@sjanssen2 The code did pass flake8 when I produced it. Maybe there is some new standard? Should I pull `biocore:master` and fix and pull request?

**Comment by qiyunzhu** [comment]
@sjanssen2 I just pulled master and tested with flake8 locally. It didn't complain...

**Pull request merged**
