### PR TITLE
Travis & Coveralls

### PR DESCRIPTION
**Pull request by sjanssen2**
Uff, a very huge PR - sorry.
I tried to set up everything we need to have automated Travis build tests and Coverall reports for the microprot repository. I used Zech's micronota as template. Since I don't have admin rights for microprot @tkosciol need to add this repo in biocore to Travis: https://docs.travis-ci.com/user/getting-started/

Furthermore, please check if 
a) the two files microprot/scripts/._contacts_precision.py and microprot/scripts/._find_contacts.py can be deleted
b) it's OK to rename the top level dir "test" into "tests"
c) I had naming issues for functions "calc_distance" and "get_PDB_coordinates", please check if my replacements still match to the right functionalities

### CODE REVIEW

**Comment by mortonjt** [comment]
👍 Looks good to go.

**Comment by qiyunzhu** [comment]
Awesome! Thanks @sjanssen2

**Comment by tkosciol** [comment]
Stefan, this looks good. We can delete ._* files, no problem.
Actually, we can also delete `contacts_precision.py` and `find_contacts.py` scripts, as their functionalities are now ported to `contacts.py` and I left them just for legacy purposes.

**Comment by tkosciol** [comment]
I also activate microprot in Travis. Let me know if it works as expected.

**Pull request merged**
